### ISSUE TITLE
Method newPlayers doesn't change players

### ISSUE THREAD

**Issue by h3lix** [gmoutsin/Compromise#6]
The method `newPlayers(self, playerA, playerB)` in CompromiseGame never seems to overwrite `self.redPlayer` or `self.greenPlayer` within the method and just resets the game with the same player objects.

**Comment by gmoutsin** [comment]
Right! I forgot to assign the players. Thanks! I fixed it, so I'm closing the issue. Feel free to open a new one if something else comes up.
