### ISSUE TITLE
while (-1 in c1) or (-1 in c2) or (-1 in c2)

### ISSUE THREAD

**Issue by m4xic** [gmoutsin/Compromise#7]
Is this line meant to be `while (-1 in c1) or (-1 in c2) or (-1 in c2)` (current) or `while (-1 in c1) or (-1 in c2) or (-1 in c3)`? (I'm not sure how much this actually changes the game, I just noticed it while scrolling through :))

https://github.com/gmoutsin/Compromise/blob/4bacd385a15715d82e4d1025582e0149092cd3b0/scr/CompromiseGame.py#L116

**Comment by gmoutsin** [comment]
Thanks for pointing this out. Fixed!
